### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Faris90** [CommunityDiep/server#9]
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
How could I fix this

**Comment by vns-123** [comment]
in which file are you getting the error? None of the files "seem" to have any errors.

**Comment by haykam821** [comment]
May I know which version of Node.js you have installed? You can find out by running this command:

```bash
node -v
```

**Comment by Faris90** [comment]
node.js version 6.11.2

**Comment by haykam821** [comment]
That is a very outdated version of Node.js. Can you update to the latest, version 9.11.1 (yes, you’re a few major versions behind) and see if it works?
